[package]
name = "byters"
version = "0.2.1"
edition = "2024"
license = "MIT"
description = "some small quality of life utilities to work with bits."
repository = "https://github.com/philmish/byters"
homepage = "https://github.com/philmish/byters"
readme = "README.md"

[dependencies]
